import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import  { GTWalsheimPro, inter } from "../../public/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GTWalsheimPro.variable} ${inter.variable}`}>
      <body className="font-inter">{children}</body>
    </html>
  );
}
